version: 0.2


phases:
  build:
    commands:
      - apt-get install -y docker
      - chmod 777 /var/run/docker.sock.
      - docker build -t babu .
      - docker push 470727887694.dkr.ecr.us-east-1.amazonaws.com/chaitanya-demo:470727887694.dkr.ecr.us-east-1.amazonaws.com/chaitanya-demo:1.0
      
