version: 0.2


phases:
  install:
    commands:
      - echo Entered the install phase...
      - apt-get -y update
      - apt-get install -y maven
      - curl -fsSL https://get.docker.com -o get-docker.sh
      - sh get-docker.sh
      
  
  build:
    commands:
      - docker build -t babu .
      - docker push 470727887694.dkr.ecr.us-east-1.amazonaws.com/chaitanya-demo:470727887694.dkr.ecr.us-east-1.amazonaws.com/chaitanya-demo:1.0
      
